### ISSUE TITLE
"Load IPAdapter SD3 Model" node need protobuf 3.20.x and confuse with other nodes( >protobuf 4.25)

### ISSUE THREAD

**Issue by coddz** [Slickytail/ComfyUI-InstantX-IPAdapter-SD3#4]
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

pytorch version: 2.3.1+cu121
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using xformers cross attention

![image](https://github.com/user-attachments/assets/8f416196-7c7f-4494-a0cc-f0ff30a73a3c)

Loading InstantX IPAdapter SD3 model.
!!! Exception during processing !!! Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "F:\ComfyUI-aki-v1.4\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI-aki-v1.4\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI-aki-v1.4\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI-aki-v1.4\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-InstantX-IPAdapter-SD3\nodes.py", line 154, in load_model
    model = SD3IPAdapter(clip_vision, ipadapter, provider)
  File "F:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-InstantX-IPAdapter-SD3\nodes.py", line 74, in __init__
    self.processor = AutoProcessor.from_pretrained(encoder_path)
  File "F:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\models\auto\processing_auto.py", line 328, in from_pretrained
    return processor_class.from_pretrained(
  File "F:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\processing_utils.py", line 944, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "F:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\processing_utils.py", line 990, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
  File "F:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\tokenization_utils_base.py", line 2213, in from_pretrained
    return cls._from_pretrained(
  File "F:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\tokenization_utils_base.py", line 2447, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "F:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\models\siglip\tokenization_siglip.py", line 123, in __init__
    self.sp_model = self.get_spm_processor()
  File "F:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\models\siglip\tokenization_siglip.py", line 141, in get_spm_processor
    model_pb2 = import_protobuf()
  File "F:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\convert_slow_tokenizer.py", line 38, in import_protobuf
    from sentencepiece import sentencepiece_model_pb2
  File "F:\ComfyUI-aki-v1.4\python\lib\site-packages\sentencepiece\sentencepiece_model_pb2.py", line 34, in <module>
    _descriptor.EnumValueDescriptor(
  File "F:\ComfyUI-aki-v1.4\python\lib\site-packages\google\protobuf\descriptor.py", line 920, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by coddz** [comment]
when I down the protobuf version to 3.20.3，start comfyui and autoupdate protobuf to zhe newest one (5.29.1)

**Comment by coddz** [comment]
the temporal method using sd3 ipa is changing the version of the transformers and sentencepiece:
python.exe -m pip install --upgrade sentencepiece                      -----0.2.0
python.exe -m pip install --upgrade transformers                         ----4.47.0

maybe we can adjust the requirements.txt?

**Comment by Slickytail** [comment]
Hello, I've removed the version requirements.  
I've also removed the need for sentencepiece and protobuf.  
You can feel free to install whichever version of transformers works with your other installed nodes. We only use transformers for the siglip model.
